// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Option': typeof import("../../components/Option.vue")['default'],
    'CardName': typeof import("../../components/Card/Name.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export {}
